#### 늘배움 강좌 정보 ####

ALTER TABLE NILE.TBCMS_COURSE_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE NILE.TBCMS_COURSE_INFO CASCADE CONSTRAINTS;


CREATE TABLE HR.TBCMS_COURSE_INFO
(
  COURSE_ID               VARCHAR2(200 BYTE)    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE NILE.TBCMS_COURSE_INFO
(
  COURSE_ID               VARCHAR2(200 BYTE)    NOT NULL,
  INST_ID                 VARCHAR2(15 BYTE),
  CON_COURSE_ID           VARCHAR2(32 BYTE),
  CON_INST_ID             VARCHAR2(16 BYTE),
  SIDO_CD                 VARCHAR2(10 BYTE),
  SIGUNGU_CD              VARCHAR2(10 BYTE),
  COURSE_NM               VARCHAR2(500 BYTE),
  COURSE_DESC_URL         VARCHAR2(4000 BYTE),
  COURSE_PTTN_CD          VARCHAR2(2 BYTE),
  GENERATION_CLASS_CD     VARCHAR2(10 BYTE),
  STRATUM_CLASS_CD        VARCHAR2(10 BYTE),
  EXTRA_CHARGE_CONTENT    VARCHAR2(200 BYTE),
  EDU_CYCLE_CONTENT       VARCHAR2(200 BYTE),
  EDU_QUOTA_CNT           NVARCHAR2(200),
  COURSE_START_DT         DATE,
  COURSE_END_DT           DATE,
  RECEIVE_START_DT        DATE,
  RECEIVE_END_DT          DATE,
  EDU_TM                  VARCHAR2(200 BYTE),
  EDU_LOCATION_DESC       VARCHAR2(4000 BYTE),
  INQUIRY_TEL_NO          VARCHAR2(100 BYTE),
  TEACHER_PERNM           VARCHAR2(200 BYTE),
  INFO_MNG_INST_ID        VARCHAR2(100 BYTE),
  INFO_INP_INST_ID        VARCHAR2(100 BYTE),
  TAG                     VARCHAR2(4000 BYTE),
  JOB_ABILITY_COURSE_YN   VARCHAR2(1 BYTE),
  CB_EVAL_ACCEPT_YN       VARCHAR2(1 BYTE),
  ALL_EVAL_ACCEPT_YN      VARCHAR2(1 BYTE),
  LANG_CD                 VARCHAR2(10 BYTE),
  STUDY_OS_NM             VARCHAR2(200 BYTE),
  STUDY_WEB_BROWSER_NM    VARCHAR2(100 BYTE),
  STUDY_DEVICE_NM         VARCHAR2(100 BYTE),
  VSL_HANDICAP_SUPP_YN    VARCHAR2(1 BYTE),
  HRG_HANDICAP_SUPP_YN    VARCHAR2(1 BYTE),
  COURSE_CLASS1_CD        VARCHAR2(2 BYTE),
  COURSE_CLASS2_CD        VARCHAR2(2 BYTE),
  COURSE_THUMBNAIL_URL    VARCHAR2(200 BYTE),
  ATTCH_IMG_ID            VARCHAR2(15 BYTE),
  EDU_TARGET_CD           VARCHAR2(200 BYTE),
  ENROLL_APPL_METHOD_CD   VARCHAR2(50 BYTE),
  EDU_METHOD_CD           VARCHAR2(10 BYTE),
  EDU_LVLDFF_TYPE_CD      VARCHAR2(10 BYTE),
  REF_BOOK_NM             VARCHAR2(200 BYTE),
  SOURCE_DESC             VARCHAR2(200 BYTE),
  LINK_URL                VARCHAR2(4000 BYTE),
  STUDY_GOAL_CD           VARCHAR2(10 BYTE),
  REG_USER_ID             VARCHAR2(30 BYTE)     NOT NULL,
  REG_DT                  DATE                  DEFAULT SYSDATE               NOT NULL,
  UPD_USER_ID             VARCHAR2(30 BYTE),
  UPD_DT                  DATE,
  STATUS                  NUMBER,
  DEL_YN                  VARCHAR2(1 BYTE)      DEFAULT 'N'                   NOT NULL,
  COURSE_URL              VARCHAR2(1000 BYTE),
  COURSE_URL_CALL_METHOD  VARCHAR2(10 BYTE),
  MOBILE_URL              VARCHAR2(1000 BYTE),
  MOBILE_URL_CALL_METHOD  VARCHAR2(10 BYTE),
  LESSON_CNT              NUMBER                DEFAULT 0,
  CON_ID                  VARCHAR2(15 BYTE),
  COURSE_DESC             VARCHAR2(4000 BYTE),
  ENROLL_AMT              VARCHAR2(200 BYTE),
  SITE_ID                 VARCHAR2(15 BYTE),
  COURSE_AGE_GRP          VARCHAR2(1 BYTE)      DEFAULT 1,
  STUDY_TOTAL_TM          NUMBER
)
TABLESPACE NILE_DAT
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          39M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE NILE.TBCMS_COURSE_INFO IS '강좌정보';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_ID IS '강좌아이디';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.INST_ID IS '기관아이디';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.CON_COURSE_ID IS '연계강좌아이디';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.CON_INST_ID IS '연계기관아이디';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.SIDO_CD IS '시도코드';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.SIGUNGU_CD IS '시구군코드';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_NM IS '강좌명';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_DESC_URL IS '강좌설명URL';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_PTTN_CD IS '강좌유형코드';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.GENERATION_CLASS_CD IS '세대분류코드';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.STRATUM_CLASS_CD IS '계층분류코드';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.EXTRA_CHARGE_CONTENT IS '부대비용내용';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.EDU_CYCLE_CONTENT IS '교육주기';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.EDU_QUOTA_CNT IS '교육인원수';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_START_DT IS '강좌시작일시';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_END_DT IS '강좌종료일시';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.RECEIVE_START_DT IS '접수시작일시';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.RECEIVE_END_DT IS '접수종료일시';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.EDU_TM IS '교육시간';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.EDU_LOCATION_DESC IS '교육장소설명';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.INQUIRY_TEL_NO IS '문의전화번호';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.TEACHER_PERNM IS '강사성명';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.INFO_MNG_INST_ID IS '정보관리기관아이디';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.INFO_INP_INST_ID IS '정보입력기관아이디';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.TAG IS '태그';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.JOB_ABILITY_COURSE_YN IS '직업능력개발훈련비지원강좌여부';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.CB_EVAL_ACCEPT_YN IS '학점은행제평가인정여부';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.ALL_EVAL_ACCEPT_YN IS '평생학습계좌제평가인정여부';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.LANG_CD IS '언어';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.STUDY_OS_NM IS '학습운영체제';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.STUDY_WEB_BROWSER_NM IS '학습웹브라우저';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.STUDY_DEVICE_NM IS '학습장치';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.VSL_HANDICAP_SUPP_YN IS '시각장애지원여부';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.HRG_HANDICAP_SUPP_YN IS '청각장애지원여부';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_CLASS1_CD IS '강좌분류1코드';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_CLASS2_CD IS '강좌분류2코드';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_THUMBNAIL_URL IS '강좌썸네일URL';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.ATTCH_IMG_ID IS '첨부이미지아이디';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.EDU_TARGET_CD IS '교육대상코드';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.ENROLL_APPL_METHOD_CD IS '수강신청방법코드';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.EDU_METHOD_CD IS '교육방법코드';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.EDU_LVLDFF_TYPE_CD IS '교육난이도구분코드';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.REF_BOOK_NM IS '참고도서명';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.SOURCE_DESC IS '출처';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.LINK_URL IS '링크URL';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.STUDY_GOAL_CD IS '학습목적';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.REG_USER_ID IS '등록자아이디';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.REG_DT IS '등록일시';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.UPD_USER_ID IS '수정자아이디';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.UPD_DT IS '수정일시';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.STATUS IS '상태';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.DEL_YN IS '삭제여부';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_URL IS '강좌URL';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_URL_CALL_METHOD IS '강좌URL호출방법';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.MOBILE_URL IS '모바일URL';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.MOBILE_URL_CALL_METHOD IS '모바일URL호출방법';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.LESSON_CNT IS '차시수';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.CON_ID IS '연계아이디';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_DESC IS '강좌설명';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.ENROLL_AMT IS '수강금액';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.SITE_ID IS '사이트아이디';

COMMENT ON COLUMN NILE.TBCMS_COURSE_INFO.COURSE_AGE_GRP IS '연령대 추천강좌';



CREATE INDEX NILE.IX_TBCMS_COURSE_INFO_1 ON NILE.TBCMS_COURSE_INFO
(INST_ID)
LOGGING
TABLESPACE NILE_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX NILE.IX_TBCMS_COURSE_INFO_2 ON NILE.TBCMS_COURSE_INFO
(SIDO_CD, SIGUNGU_CD)
LOGGING
TABLESPACE NILE_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX NILE.IX_TBCMS_COURSE_INFO_3 ON NILE.TBCMS_COURSE_INFO
(COURSE_NM)
LOGGING
TABLESPACE NILE_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          4M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX NILE.IX_TBCMS_COURSE_INFO_4 ON NILE.TBCMS_COURSE_INFO
(COURSE_CLASS1_CD, COURSE_CLASS2_CD)
LOGGING
TABLESPACE NILE_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE INDEX NILE.IX_TBCMS_COURSE_INFO_5 ON NILE.TBCMS_COURSE_INFO
(COURSE_DESC)
LOGGING
TABLESPACE NILE_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   167
STORAGE    (
            INITIAL          16M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX NILE.PK_TBCMS_COURSE_INFO ON NILE.TBCMS_COURSE_INFO
(COURSE_ID)
LOGGING
TABLESPACE NILE_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE NILE.TBCMS_COURSE_INFO ADD (
  CONSTRAINT TBCMS_COURSE_INFO_PK
  PRIMARY KEY
  (COURSE_ID)
  USING INDEX NILE.PK_TBCMS_COURSE_INFO
  ENABLE VALIDATE);

